name       : minigbm
version    : 1.627
release    : 1
source     :
    - git|https://chromium.googlesource.com/chromiumos/platform/minigbm : a0af30944c832c4a131553d071cc86f6e7b04d05
license    : BSD-3-Clause
component  : programming.library
summary    : Generic Buffer Management (GBM) implementation
description: |
    Generic Buffer Management (GBM) implementation
emul32     : yes
libsplit   : no
builddeps  :
    - pkgconfig32(dri)
environment: |
    export CFLAGS="${CFLAGS} -Wno-error=pointer-to-int-cast"
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-install-all-the-things.patch
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir%
